server:
  port: 9001

spring:
  application:
    name: finance_service


#  datasource:
#    url: ${SPRING_DATASOURCE_URL}
#    username: ${SPRING_DATASOURCE_USERNAME}
#    password: ${SPRING_DATASOURCE_PASSWORD}
#    hikari:
#      auto-commit: false

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#  jpa:
#    hibernate:
#      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
#    show-sql: ${SPRING_JPA_SHOW_SQL:true}
#    properties:
#      hibernate.format_sql: true
#
#  liquibase:
#    enabled: true

